window.PEOPLE = [
  {
    "id": "aaron-levie",
    "name": "Aaron Levie",
    "category": "founder",
    "achievement": "Co-founded Box",
    "achievement_year": 2005,
    "age_at_achievement": 20,
    "country_of_origin": "United States",
    "education_level": "dropout",
    "education_institution": "University of Southern California",
    "prior_failures": [],
    "story": "Started Box from his USC dorm room with a high school friend. Dropped out his sophomore year to scale it, when \"cloud storage\" was not yet a phrase anyone used.",
    "notability": "$5B+ peak market cap"
  },
  {
    "id": "adam-dangelo",
    "name": "Adam D'Angelo",
    "category": "founder",
    "achievement": "Co-founded Quora",
    "achievement_year": 2009,
    "age_at_achievement": 25,
    "country_of_origin": "United States",
    "education_level": "bachelors",
    "education_institution": "California Institute of Technology",
    "prior_failures": [],
    "story": "Mark Zuckerberg's high school best friend. Became Facebook's CTO straight out of Caltech. Left at 25 to start Quora, because the question \"what's the best way to learn anything?\" had no good answer online.",
    "notability": "$2B+ peak valuation"
  },
  {
    "id": "albert-einstein",
    "name": "Albert Einstein",
    "category": "scientist",
    "achievement": "Published his Annus Mirabilis papers, including special relativity",
    "achievement_year": 1905,
    "age_at_achievement": 26,
    "country_of_origin": "Germany",
    "education_level": "graduate",
    "education_institution": "ETH Zurich",
    "prior_failures": [
      "Failed his first entrance exam to ETH Zurich at age 16",
      "Could not find a single academic job after his PhD; took a clerk position at the Swiss patent office"
    ],
    "story": "Could not get a single academic job after his PhD. Took a clerk position at the Swiss patent office. Wrote four world-changing physics papers at 26 in his spare time.",
    "notability": "Nobel Prize in Physics (1921)"
  },
  {
    "id": "anne-boden",
    "name": "Anne Boden",
    "category": "founder",
    "achievement": "Founded Starling Bank",
    "achievement_year": 2014,
    "age_at_achievement": 54,
    "country_of_origin": "United Kingdom",
    "education_level": "graduate",
    "education_institution": "London School of Economics",
    "prior_failures": [
      "Pushed out of a top exec role at Allied Irish Banks",
      "Struggled to raise initial seed funding as a female founder over 50"
    ],
    "story": "After 30 years in traditional banking, pushed out of a top exec role. At 54 she started Starling, becoming Britain's first female founder of a $1B+ bank.",
    "notability": "$1.5B+ peak valuation"
  },
  {
    "id": "anthony-tan",
    "name": "Anthony Tan",
    "category": "founder",
    "achievement": "Co-founded Grab",
    "achievement_year": 2012,
    "age_at_achievement": 30,
    "country_of_origin": "Malaysia",
    "education_level": "graduate",
    "education_institution": "Harvard Business School",
    "prior_failures": [],
    "story": "Heir to a Malaysian car distribution dynasty who chose to start over. At 30, fresh out of Harvard, he built a taxi-booking app in Kuala Lumpur. It became Southeast Asia's largest tech company.",
    "notability": "$40B peak market cap"
  },
  {
    "id": "beyonce-knowles",
    "name": "Beyoncé",
    "category": "musician",
    "achievement": "Released her debut solo album \"Dangerously in Love\"",
    "achievement_year": 2003,
    "age_at_achievement": 21,
    "country_of_origin": "United States",
    "education_level": "no_college",
    "education_institution": null,
    "prior_failures": [
      "Girls Tyme, her first group, lost on Star Search in 1993 when she was 11"
    ],
    "story": "Her first group lost on Star Search at age 11. By 17 she was fronting Destiny's Child; by 21 her solo debut won five Grammys.",
    "notability": "32× Grammy winner, most decorated artist in Grammy history"
  },
  {
    "id": "bill-gates",
    "name": "Bill Gates",
    "category": "founder",
    "achievement": "Co-founded Microsoft",
    "achievement_year": 1975,
    "age_at_achievement": 19,
    "country_of_origin": "United States",
    "education_level": "dropout",
    "education_institution": "Harvard University",
    "prior_failures": [
      "Traf-O-Data, an early traffic-data analysis venture, struggled to find buyers and shut down"
    ],
    "story": "Co-founded Microsoft at 19 with a high-school friend, after one prior venture had quietly failed. Left Harvard sophomore year and never returned.",
    "notability": "$3.1T peak market cap"
  },
  {
    "id": "brian-armstrong",
    "name": "Brian Armstrong",
    "category": "founder",
    "achievement": "Co-founded Coinbase",
    "achievement_year": 2012,
    "age_at_achievement": 29,
    "country_of_origin": "United States",
    "education_level": "graduate",
    "education_institution": "Rice University",
    "prior_failures": [],
    "story": "An Airbnb engineer at 29 who spent evenings and weekends building Coinbase, when most people thought Bitcoin was a fad or a scam. He went on to take Coinbase public at a $100B+ valuation.",
    "notability": "$100B+ peak market cap"
  },
  {
    "id": "brian-chesky",
    "name": "Brian Chesky",
    "category": "founder",
    "achievement": "Co-founded Airbnb",
    "achievement_year": 2008,
    "age_at_achievement": 27,
    "country_of_origin": "United States",
    "education_level": "bachelors",
    "education_institution": "Rhode Island School of Design",
    "prior_failures": [],
    "story": "An industrial designer who couldn't afford rent in San Francisco. At 27, he and his roommate rented out air mattresses in their apartment to make rent. That became Airbnb.",
    "notability": "$100B+ peak market cap"
  },
  {
    "id": "daniel-ek",
    "name": "Daniel Ek",
    "category": "founder",
    "achievement": "Co-founded Spotify",
    "achievement_year": 2006,
    "age_at_achievement": 23,
    "country_of_origin": "Sweden",
    "education_level": "dropout",
    "education_institution": "KTH Royal Institute of Technology",
    "prior_failures": [],
    "story": "A 23-year-old Swede who had been programming since age 5. Built Spotify after the music industry had spent a decade losing to Napster.",
    "notability": "$100B+ peak market cap"
  },
  {
    "id": "david-velez",
    "name": "David Vélez",
    "category": "founder",
    "achievement": "Founded Nubank",
    "achievement_year": 2013,
    "age_at_achievement": 32,
    "country_of_origin": "Colombia",
    "education_level": "graduate",
    "education_institution": "Stanford Graduate School of Business",
    "prior_failures": [],
    "story": "Colombian who could not get a credit card in Brazil despite working at Sequoia. At 32, he and two co-founders started a digital bank with no branches and no fees. Nubank now serves 100 million customers.",
    "notability": "$60B peak market cap"
  },
  {
    "id": "drew-houston",
    "name": "Drew Houston",
    "category": "founder",
    "achievement": "Founded Dropbox",
    "achievement_year": 2007,
    "age_at_achievement": 24,
    "country_of_origin": "United States",
    "education_level": "bachelors",
    "education_institution": "Massachusetts Institute of Technology",
    "prior_failures": [],
    "story": "An MIT student who kept forgetting his USB stick on the bus. At 24, frustrated, he prototyped Dropbox over a single weekend.",
    "notability": "$12B peak market cap"
  },
  {
    "id": "dustin-moskovitz",
    "name": "Dustin Moskovitz",
    "category": "founder",
    "achievement": "Co-founded Asana",
    "achievement_year": 2008,
    "age_at_achievement": 24,
    "country_of_origin": "United States",
    "education_level": "dropout",
    "education_institution": "Harvard University",
    "prior_failures": [],
    "story": "Zuckerberg's college roommate. Co-founded Facebook in their dorm. Left at 24 to start Asana, betting that team coordination tools were the next big platform.",
    "notability": "$5B+ peak market cap"
  },
  {
    "id": "dylan-field",
    "name": "Dylan Field",
    "category": "founder",
    "achievement": "Co-founded Figma",
    "achievement_year": 2012,
    "age_at_achievement": 20,
    "country_of_origin": "United States",
    "education_level": "dropout",
    "education_institution": "Brown University",
    "prior_failures": [],
    "story": "Won a Thiel Fellowship at 19, dropped out of Brown, and at 20 started building a browser-based design tool when everyone said Adobe could never be beaten.",
    "notability": "$20B peak valuation"
  },
  {
    "id": "elon-musk",
    "name": "Elon Musk",
    "category": "founder",
    "achievement": "Founded SpaceX",
    "achievement_year": 2002,
    "age_at_achievement": 30,
    "country_of_origin": "South Africa",
    "education_level": "bachelors",
    "education_institution": "University of Pennsylvania",
    "prior_failures": [],
    "story": "Arrived in North America at 17 with little money. Founded Zip2 at 24 (sold for $307M), then PayPal, then SpaceX at 30, when nobody believed a private rocket company could work.",
    "notability": "$350B+ peak valuation"
  },
  {
    "id": "evan-spiegel",
    "name": "Evan Spiegel",
    "category": "founder",
    "achievement": "Co-founded Snap",
    "achievement_year": 2011,
    "age_at_achievement": 21,
    "country_of_origin": "United States",
    "education_level": "dropout",
    "education_institution": "Stanford University",
    "prior_failures": [
      "Future Freshman, an earlier college admissions tool he co-founded, quietly died"
    ],
    "story": "A 21-year-old Stanford student whose previous startup had quietly failed. Snap began as a class project his own classmates told him was a bad idea.",
    "notability": "$130B peak market cap"
  },
  {
    "id": "falguni-nayar",
    "name": "Falguni Nayar",
    "category": "founder",
    "achievement": "Founded Nykaa",
    "achievement_year": 2012,
    "age_at_achievement": 50,
    "country_of_origin": "India",
    "education_level": "graduate",
    "education_institution": "IIM Ahmedabad",
    "prior_failures": [],
    "story": "Spent 20 years at a Mumbai investment bank. At 50, with twin teenage kids at home, she left to start an online beauty retailer in a country where the category barely existed. Took Nykaa public at a $13B valuation.",
    "notability": "$13B IPO valuation"
  },
  {
    "id": "forrest-li",
    "name": "Forrest Li",
    "category": "founder",
    "achievement": "Founded Sea (Garena and Shopee)",
    "achievement_year": 2009,
    "age_at_achievement": 32,
    "country_of_origin": "China",
    "education_level": "graduate",
    "education_institution": "Stanford Graduate School of Business",
    "prior_failures": [],
    "story": "Chinese-born, watched Steve Jobs give the Stanford commencement and decided to start something. At 32, in Singapore, he launched what became Southeast Asia's gaming and e-commerce giant.",
    "notability": "$200B+ peak market cap"
  },
  {
    "id": "harland-sanders",
    "name": "Harland \"Colonel\" Sanders",
    "category": "founder",
    "achievement": "Began franchising Kentucky Fried Chicken",
    "achievement_year": 1952,
    "age_at_achievement": 62,
    "country_of_origin": "United States",
    "education_level": "no_college",
    "education_institution": null,
    "prior_failures": [
      "Quit school in 7th grade",
      "Fired from a dozen jobs by his 30s",
      "His Corbin, Kentucky restaurant went under when a new highway bypassed the town",
      "Reportedly heard 1,009 rejections of his chicken recipe before the first franchise yes"
    ],
    "story": "Lost his restaurant at 62 when a new highway bypassed his town. Got in his car with a pressure cooker and his recipe; reportedly heard 1,009 \"no\"s before the first franchise yes.",
    "notability": "KFC now operates in 145 countries"
  },
  {
    "id": "jack-dorsey",
    "name": "Jack Dorsey",
    "category": "founder",
    "achievement": "Co-founded Twitter",
    "achievement_year": 2006,
    "age_at_achievement": 29,
    "country_of_origin": "United States",
    "education_level": "dropout",
    "education_institution": "New York University",
    "prior_failures": [
      "Fired from Odeo (the company Twitter was incubated inside) before being brought back as Twitter CEO"
    ],
    "story": "Dropped out of NYU and worked as a programmer-for-hire. At 29 he sketched the idea for Twitter on a notepad while working at a podcasting startup that was failing.",
    "notability": "$50B+ peak market cap (pre-X)"
  },
  {
    "id": "jack-ma",
    "name": "Jack Ma",
    "category": "founder",
    "achievement": "Founded Alibaba",
    "achievement_year": 1999,
    "age_at_achievement": 34,
    "country_of_origin": "China",
    "education_level": "bachelors",
    "education_institution": "Hangzhou Normal University",
    "prior_failures": [
      "Failed the Chinese college entrance exam twice",
      "Rejected from 30+ jobs including a KFC manager role (only one of 24 applicants turned down)",
      "China Pages, his first internet venture, lost control to a state telecom partner"
    ],
    "story": "Rejected from Harvard ten times. Failed the Chinese college entrance exam twice. At 34, an English teacher with no tech background, he gathered 17 friends in his apartment and started Alibaba.",
    "notability": "$830B peak market cap"
  },
  {
    "id": "james-dyson",
    "name": "James Dyson",
    "category": "founder",
    "achievement": "Founded Dyson",
    "achievement_year": 1991,
    "age_at_achievement": 44,
    "country_of_origin": "United Kingdom",
    "education_level": "graduate",
    "education_institution": "Royal College of Art",
    "prior_failures": [
      "Forced out of his own first company, Ballbarrow, in his 30s",
      "Spent 5 years building 5,127 failed cyclone vacuum prototypes before one worked"
    ],
    "story": "Built 5,127 failed prototypes before his cyclone vacuum worked. He was 44 and near-bankrupt before Dyson Ltd became a real company.",
    "notability": "$30B+ private valuation"
  },
  {
    "id": "jeff-bezos",
    "name": "Jeff Bezos",
    "category": "founder",
    "achievement": "Founded Amazon",
    "achievement_year": 1994,
    "age_at_achievement": 30,
    "country_of_origin": "United States",
    "education_level": "bachelors",
    "education_institution": "Princeton University",
    "prior_failures": [],
    "story": "Quit a high-paying Wall Street job at 30 to drive across the country and sell books out of a Seattle garage. His parents invested most of their savings.",
    "notability": "$2T+ peak market cap"
  },
  {
    "id": "jensen-huang",
    "name": "Jensen Huang",
    "category": "founder",
    "achievement": "Co-founded NVIDIA",
    "achievement_year": 1993,
    "age_at_achievement": 30,
    "country_of_origin": "Taiwan",
    "education_level": "graduate",
    "education_institution": "Stanford University",
    "prior_failures": [
      "Sent alone with his brother to a Kentucky reform school at age 10 after a mix-up; bullied, and worked as a janitor there"
    ],
    "story": "Born in Taiwan, sent alone with his brother to a Kentucky boarding school at 10. Washed dishes at Denny's through college. At 30, he pitched NVIDIA in a Denny's booth.",
    "notability": "$3T+ peak market cap"
  },
  {
    "id": "jk-rowling",
    "name": "J.K. Rowling",
    "category": "author",
    "achievement": "Published \"Harry Potter and the Philosopher's Stone\"",
    "achievement_year": 1997,
    "age_at_achievement": 32,
    "country_of_origin": "United Kingdom",
    "education_level": "bachelors",
    "education_institution": "University of Exeter",
    "prior_failures": [
      "Rejected by 12 publishers before Bloomsbury accepted Harry Potter",
      "Single mother on welfare, diagnosed with clinical depression while writing the manuscript"
    ],
    "story": "Single mother on welfare, writing in cafes while her daughter slept. Rejected by 12 publishers before Bloomsbury bought Harry Potter at 32. Over 600 million copies sold.",
    "notability": "600M+ books sold"
  },
  {
    "id": "john-collison",
    "name": "John Collison",
    "category": "founder",
    "achievement": "Co-founded Stripe",
    "achievement_year": 2010,
    "age_at_achievement": 20,
    "country_of_origin": "Ireland",
    "education_level": "dropout",
    "education_institution": "Harvard University",
    "prior_failures": [],
    "story": "Dropped out of Harvard at 20 to start Stripe with his older brother. He had already sold his first company at 17.",
    "notability": "$95B peak valuation"
  },
  {
    "id": "larry-ellison",
    "name": "Larry Ellison",
    "category": "founder",
    "achievement": "Co-founded Oracle",
    "achievement_year": 1977,
    "age_at_achievement": 33,
    "country_of_origin": "United States",
    "education_level": "dropout",
    "education_institution": "University of Chicago",
    "prior_failures": [
      "Dropped out of two universities (Illinois and Chicago) by age 22",
      "Drifted through eight years of low-paying tech jobs before founding Oracle"
    ],
    "story": "Adopted at nine months old by a working-class family in Chicago. Dropped out of two universities. Drifted through eight years of low-paying tech jobs before starting Oracle at 33 with $2,000.",
    "notability": "$500B+ peak market cap"
  },
  {
    "id": "larry-page",
    "name": "Larry Page",
    "category": "founder",
    "achievement": "Co-founded Google (Alphabet)",
    "achievement_year": 1998,
    "age_at_achievement": 25,
    "country_of_origin": "United States",
    "education_level": "bachelors",
    "education_institution": "Stanford University",
    "prior_failures": [],
    "story": "A 25-year-old Stanford PhD student who built a search algorithm as a research side project. Took a leave of absence to grow Google; never went back.",
    "notability": "$2.1T peak market cap"
  },
  {
    "id": "lebron-james",
    "name": "LeBron James",
    "category": "athlete",
    "achievement": "Won his first NBA Championship",
    "achievement_year": 2012,
    "age_at_achievement": 27,
    "country_of_origin": "United States",
    "education_level": "no_college",
    "education_institution": null,
    "prior_failures": [
      "Lost the 2007 NBA Finals in a sweep and was ridiculed for years",
      "Lost the 2011 NBA Finals in the backlash of \"The Decision\""
    ],
    "story": "Raised by a single teenage mother in Akron, Ohio. Drafted #1 straight out of high school at 18, but it took him until 27, after years of public ridicule, to win his first ring.",
    "notability": "4× NBA Champion, 4× Finals MVP"
  },
  {
    "id": "lionel-messi",
    "name": "Lionel Messi",
    "category": "athlete",
    "achievement": "Won his first Ballon d'Or",
    "achievement_year": 2009,
    "age_at_achievement": 22,
    "country_of_origin": "Argentina",
    "education_level": "no_college",
    "education_institution": null,
    "prior_failures": [
      "Diagnosed with a growth hormone deficiency at 11; local Argentine clubs would not pay for treatment"
    ],
    "story": "Diagnosed with a growth hormone deficiency at 11. Local Argentine clubs would not pay for treatment; Barcelona signed him on a napkin and moved his whole family to Spain.",
    "notability": "8× Ballon d'Or, World Cup winner"
  },
  {
    "id": "luis-von-ahn",
    "name": "Luis von Ahn",
    "category": "founder",
    "achievement": "Co-founded Duolingo",
    "achievement_year": 2011,
    "age_at_achievement": 33,
    "country_of_origin": "Guatemala",
    "education_level": "graduate",
    "education_institution": "Carnegie Mellon University",
    "prior_failures": [],
    "story": "Grew up in Guatemala City, where private schools cost more than most families earned in a year. He invented CAPTCHA, sold reCAPTCHA to Google at 30, then at 33 built Duolingo to give the world free language education.",
    "notability": "$10B+ peak market cap"
  },
  {
    "id": "marcos-galperin",
    "name": "Marcos Galperin",
    "category": "founder",
    "achievement": "Co-founded MercadoLibre",
    "achievement_year": 1999,
    "age_at_achievement": 27,
    "country_of_origin": "Argentina",
    "education_level": "graduate",
    "education_institution": "Stanford Graduate School of Business",
    "prior_failures": [],
    "story": "Stanford MBA who turned down Wall Street to build Latin America's eBay. Survived the dot-com bust, an Argentine economic collapse, and a decade of skeptics. MercadoLibre is now Latin America's most valuable company.",
    "notability": "$100B+ peak market cap"
  },
  {
    "id": "marie-curie",
    "name": "Marie Curie",
    "category": "scientist",
    "achievement": "Won the Nobel Prize in Physics",
    "achievement_year": 1903,
    "age_at_achievement": 36,
    "country_of_origin": "Poland",
    "education_level": "graduate",
    "education_institution": "University of Paris (Sorbonne)",
    "prior_failures": [
      "Banned from Polish universities because she was a woman; saved for years to study in Paris",
      "Worked as a governess for six years to fund her sister's medical studies first"
    ],
    "story": "Poland banned women from university, so she worked as a governess for six years to save the fare to Paris. Won the Nobel Prize at 36; the first person ever to win two in different sciences.",
    "notability": "Two-time Nobel laureate (Physics, Chemistry)"
  },
  {
    "id": "mark-zuckerberg",
    "name": "Mark Zuckerberg",
    "category": "founder",
    "achievement": "Founded Facebook (Meta)",
    "achievement_year": 2004,
    "age_at_achievement": 19,
    "country_of_origin": "United States",
    "education_level": "dropout",
    "education_institution": "Harvard University",
    "prior_failures": [],
    "story": "Built Facebook from his Harvard dorm room at 19. Dropped out his sophomore year to grow it; today Meta is worth over a trillion dollars.",
    "notability": "$1.3T+ peak market cap"
  },
  {
    "id": "melanie-perkins",
    "name": "Melanie Perkins",
    "category": "founder",
    "achievement": "Co-founded Canva",
    "achievement_year": 2013,
    "age_at_achievement": 26,
    "country_of_origin": "Australia",
    "education_level": "bachelors",
    "education_institution": "University of Western Australia",
    "prior_failures": [],
    "story": "A design student in Perth who taught yearbook software on the side. By 26 she had built a working Canva prototype, after more than 100 investor rejections.",
    "notability": "$40B peak valuation"
  },
  {
    "id": "michael-dell",
    "name": "Michael Dell",
    "category": "founder",
    "achievement": "Founded Dell Computer",
    "achievement_year": 1984,
    "age_at_achievement": 19,
    "country_of_origin": "United States",
    "education_level": "dropout",
    "education_institution": "University of Texas at Austin",
    "prior_failures": [],
    "story": "Sold upgraded PCs out of his UT Austin dorm room with $1,000 in savings. Dropped out his freshman year. By 27 he was the youngest CEO of a Fortune 500.",
    "notability": "$150B+ peak market cap"
  },
  {
    "id": "michael-jordan",
    "name": "Michael Jordan",
    "category": "athlete",
    "achievement": "Won his first NBA Championship",
    "achievement_year": 1991,
    "age_at_achievement": 28,
    "country_of_origin": "United States",
    "education_level": "bachelors",
    "education_institution": "University of North Carolina at Chapel Hill",
    "prior_failures": [
      "Famously cut from his high school varsity basketball team as a sophomore"
    ],
    "story": "Cut from his high school varsity team as a sophomore. Used the rejection as fuel, walked on at UNC, and at 28 won the first of six NBA championships.",
    "notability": "6× NBA Champion, 5× MVP"
  },
  {
    "id": "niklas-zennstrom",
    "name": "Niklas Zennström",
    "category": "founder",
    "achievement": "Co-founded Skype",
    "achievement_year": 2003,
    "age_at_achievement": 37,
    "country_of_origin": "Sweden",
    "education_level": "graduate",
    "education_institution": "Uppsala University",
    "prior_failures": [
      "Kazaa, his prior peer-to-peer music platform, was sued by every major record label"
    ],
    "story": "A 37-year-old Swede whose previous company had been sued by every major record label. Used the same peer-to-peer technology to build Skype. Microsoft bought it for $8.5B.",
    "notability": "$8.5B sale to Microsoft"
  },
  {
    "id": "niraj-shah",
    "name": "Niraj Shah",
    "category": "founder",
    "achievement": "Co-founded Wayfair",
    "achievement_year": 2002,
    "age_at_achievement": 28,
    "country_of_origin": "United States",
    "education_level": "bachelors",
    "education_institution": "Cornell University",
    "prior_failures": [
      "Spinners, his first startup, was acquired small and forgotten",
      "iOwn, his second startup, survived but neither made him rich"
    ],
    "story": "Two prior startups had small exits, neither making him rich. At 28 he and his college roommate started selling stereo racks online from a single domain name. It became Wayfair.",
    "notability": "$30B peak market cap"
  },
  {
    "id": "oprah-winfrey",
    "name": "Oprah Winfrey",
    "category": "media",
    "achievement": "Launched \"The Oprah Winfrey Show\" nationally",
    "achievement_year": 1986,
    "age_at_achievement": 32,
    "country_of_origin": "United States",
    "education_level": "bachelors",
    "education_institution": "Tennessee State University",
    "prior_failures": [
      "Born to a teenage single mother in rural Mississippi poverty",
      "Suffered childhood abuse; ran away from home at 13",
      "Demoted from a Baltimore news anchor job for being \"unfit for television\""
    ],
    "story": "Born to a 17-year-old single mother in rural Mississippi. Survived abuse and poverty. A Baltimore station fired her at 22 as \"unfit for television.\" By 32 she had the highest-rated talk show in America.",
    "notability": "First Black woman billionaire in the US"
  },
  {
    "id": "patrick-collison",
    "name": "Patrick Collison",
    "category": "founder",
    "achievement": "Co-founded Stripe",
    "achievement_year": 2010,
    "age_at_achievement": 22,
    "country_of_origin": "Ireland",
    "education_level": "dropout",
    "education_institution": "Massachusetts Institute of Technology",
    "prior_failures": [],
    "story": "Won Young Scientist of the Year in Ireland at 16. Dropped out of MIT at 22 to start Stripe with his teenage brother. They had already sold one company together.",
    "notability": "$95B peak valuation"
  },
  {
    "id": "pierre-omidyar",
    "name": "Pierre Omidyar",
    "category": "founder",
    "achievement": "Founded eBay",
    "achievement_year": 1995,
    "age_at_achievement": 28,
    "country_of_origin": "France",
    "education_level": "bachelors",
    "education_institution": "Tufts University",
    "prior_failures": [],
    "story": "Born in Paris to Iranian parents, raised in the US. At 28, he built the first version of eBay over a weekend on his personal website, just to see if anyone would use it.",
    "notability": "$70B+ peak market cap"
  },
  {
    "id": "reed-hastings",
    "name": "Reed Hastings",
    "category": "founder",
    "achievement": "Co-founded Netflix",
    "achievement_year": 1997,
    "age_at_achievement": 37,
    "country_of_origin": "United States",
    "education_level": "graduate",
    "education_institution": "Stanford University",
    "prior_failures": [],
    "story": "A former Peace Corps math teacher who had already built and sold one company. At 37, after being charged a $40 late fee on a Blockbuster rental, he started Netflix.",
    "notability": "$300B+ peak market cap"
  },
  {
    "id": "reid-hoffman",
    "name": "Reid Hoffman",
    "category": "founder",
    "achievement": "Co-founded LinkedIn",
    "achievement_year": 2002,
    "age_at_achievement": 35,
    "country_of_origin": "United States",
    "education_level": "graduate",
    "education_institution": "Oxford University",
    "prior_failures": [
      "SocialNet, his 1997 attempt at an online social network, never gained traction and shut down"
    ],
    "story": "His first social network company, SocialNet, failed in the late 1990s. He joined PayPal, learned from the exit, and at 35 started LinkedIn with what he had learned.",
    "notability": "$26B sale to Microsoft"
  },
  {
    "id": "sam-altman",
    "name": "Sam Altman",
    "category": "founder",
    "achievement": "Co-founded OpenAI",
    "achievement_year": 2015,
    "age_at_achievement": 30,
    "country_of_origin": "United States",
    "education_level": "dropout",
    "education_institution": "Stanford University",
    "prior_failures": [],
    "story": "Dropped out of Stanford at 19 to build Loopt (sold for $43M). Co-founded OpenAI a decade later at 30, when most thought general-purpose AI was decades away.",
    "notability": "$500B+ peak valuation"
  },
  {
    "id": "sara-blakely",
    "name": "Sara Blakely",
    "category": "founder",
    "achievement": "Founded Spanx",
    "achievement_year": 2000,
    "age_at_achievement": 29,
    "country_of_origin": "United States",
    "education_level": "bachelors",
    "education_institution": "Florida State University",
    "prior_failures": [
      "Failed the LSAT twice and abandoned plans for law school"
    ],
    "story": "Sold fax machines door to door for seven years. At 29, with $5,000 in savings, no business or fashion training, and no investors, she started Spanx.",
    "notability": "$1.2B+ peak valuation"
  },
  {
    "id": "sebastian-siemiatkowski",
    "name": "Sebastian Siemiatkowski",
    "category": "founder",
    "achievement": "Co-founded Klarna",
    "achievement_year": 2005,
    "age_at_achievement": 24,
    "country_of_origin": "Sweden",
    "education_level": "bachelors",
    "education_institution": "Stockholm School of Economics",
    "prior_failures": [],
    "story": "Polish-Swedish son of immigrants, working part-time at a Burger King while studying. At 24, he and two classmates pitched a \"buy now, pay later\" idea their professors said would never work.",
    "notability": "$45B peak valuation"
  },
  {
    "id": "serena-williams",
    "name": "Serena Williams",
    "category": "athlete",
    "achievement": "Won her first Grand Slam (US Open)",
    "achievement_year": 1999,
    "age_at_achievement": 17,
    "country_of_origin": "United States",
    "education_level": "no_college",
    "education_institution": null,
    "prior_failures": [],
    "story": "Trained on cracked public courts in Compton with her sister. Won her first US Open at 17, the start of 23 Grand Slam singles titles.",
    "notability": "23 Grand Slam singles titles"
  },
  {
    "id": "sergey-brin",
    "name": "Sergey Brin",
    "category": "founder",
    "achievement": "Co-founded Google (Alphabet)",
    "achievement_year": 1998,
    "age_at_achievement": 24,
    "country_of_origin": "Russia",
    "education_level": "bachelors",
    "education_institution": "Stanford University",
    "prior_failures": [],
    "story": "Born in Moscow, immigrated to the US at age 6. At 24, a Stanford PhD student cataloging web links in a campus office. He never finished the PhD.",
    "notability": "$2.1T peak market cap"
  },
  {
    "id": "simone-biles",
    "name": "Simone Biles",
    "category": "athlete",
    "achievement": "Won her first World All-Around Championship",
    "achievement_year": 2013,
    "age_at_achievement": 16,
    "country_of_origin": "United States",
    "education_level": "no_college",
    "education_institution": null,
    "prior_failures": [],
    "story": "Spent her early years in foster care before being adopted by her grandparents. At 16 she won her first World All-Around title; she is now the most decorated gymnast in history.",
    "notability": "11× World Champion, 7× Olympic medalist"
  },
  {
    "id": "stephen-king",
    "name": "Stephen King",
    "category": "author",
    "achievement": "Published his first novel, \"Carrie\"",
    "achievement_year": 1974,
    "age_at_achievement": 26,
    "country_of_origin": "United States",
    "education_level": "bachelors",
    "education_institution": "University of Maine",
    "prior_failures": [
      "Over 30 rejection slips for short stories, which he kept pinned to his bedroom wall",
      "Threw the Carrie manuscript in the trash; his wife Tabitha rescued it"
    ],
    "story": "Working as a high school English teacher and living in a trailer with two kids. Threw the Carrie manuscript in the trash; his wife pulled it out and made him finish it. Published at 26.",
    "notability": "400M+ books sold"
  },
  {
    "id": "steve-jobs",
    "name": "Steve Jobs",
    "category": "founder",
    "achievement": "Co-founded Apple",
    "achievement_year": 1976,
    "age_at_achievement": 21,
    "country_of_origin": "United States",
    "education_level": "dropout",
    "education_institution": "Reed College",
    "prior_failures": [],
    "story": "Started Apple in his parents' garage at 21, with no degree. Reed College had been an 18-month experiment he had already walked away from.",
    "notability": "$3.5T+ peak market cap"
  },
  {
    "id": "steven-spielberg",
    "name": "Steven Spielberg",
    "category": "director",
    "achievement": "Directed \"Jaws\"",
    "achievement_year": 1975,
    "age_at_achievement": 28,
    "country_of_origin": "United States",
    "education_level": "bachelors",
    "education_institution": "California State University, Long Beach",
    "prior_failures": [
      "Rejected by the USC School of Cinematic Arts three times"
    ],
    "story": "Rejected by USC film school three times. Snuck onto the Universal Studios lot, found an empty office, and pretended he worked there. At 28 he directed Jaws and invented the summer blockbuster.",
    "notability": "3× Oscar winner, $10B+ in box office"
  },
  {
    "id": "stewart-butterfield",
    "name": "Stewart Butterfield",
    "category": "founder",
    "achievement": "Co-founded Slack",
    "achievement_year": 2013,
    "age_at_achievement": 40,
    "country_of_origin": "Canada",
    "education_level": "graduate",
    "education_institution": "University of Cambridge",
    "prior_failures": [
      "Game Neverending, his first online game project, was shut down before pivoting to Flickr",
      "Glitch, his second online game project, was shut down before pivoting to Slack"
    ],
    "story": "Two failed online games. Both times he pivoted what remained: the first became Flickr, the second became Slack. Slack sold to Salesforce for $27B.",
    "notability": "$27B sale to Salesforce"
  },
  {
    "id": "taylor-swift",
    "name": "Taylor Swift",
    "category": "musician",
    "achievement": "Released her debut album",
    "achievement_year": 2006,
    "age_at_achievement": 16,
    "country_of_origin": "United States",
    "education_level": "no_college",
    "education_institution": null,
    "prior_failures": [
      "Dropped by RCA Records at 14 when she insisted on writing her own songs"
    ],
    "story": "Rejected by RCA Records at 14 when she refused to record other people's songs. Moved her family from Pennsylvania to Nashville and released her debut at 16; her later albums became the only ones by any artist to all hit #1.",
    "notability": "14× Grammy winner, billionaire artist"
  },
  {
    "id": "tobi-lutke",
    "name": "Tobi Lütke",
    "category": "founder",
    "achievement": "Founded Shopify",
    "achievement_year": 2006,
    "age_at_achievement": 26,
    "country_of_origin": "Germany",
    "education_level": "no_college",
    "education_institution": null,
    "prior_failures": [],
    "story": "A 26-year-old German-Canadian who never went to college; he was apprenticeship-trained. Built Shopify because the platform he wanted for selling snowboards didn't exist.",
    "notability": "$200B+ peak market cap"
  },
  {
    "id": "tom-brady",
    "name": "Tom Brady",
    "category": "athlete",
    "achievement": "Won his first Super Bowl as MVP",
    "achievement_year": 2002,
    "age_at_achievement": 24,
    "country_of_origin": "United States",
    "education_level": "bachelors",
    "education_institution": "University of Michigan",
    "prior_failures": [
      "Picked 199th in the NFL Draft (6th round); six quarterbacks were taken ahead of him",
      "Sat behind two QBs at Michigan and considered transferring"
    ],
    "story": "The 199th pick of the 2000 NFL Draft. Spent his rookie year on the bench. Got the starting job by accident at 24, won the Super Bowl, and never looked back: 7 rings, more than any team in history.",
    "notability": "7× Super Bowl Champion, 5× MVP"
  },
  {
    "id": "usain-bolt",
    "name": "Usain Bolt",
    "category": "athlete",
    "achievement": "Won three Olympic golds at the Beijing Games",
    "achievement_year": 2008,
    "age_at_achievement": 21,
    "country_of_origin": "Jamaica",
    "education_level": "no_college",
    "education_institution": null,
    "prior_failures": [],
    "story": "Grew up in rural Jamaica, the son of a grocer. At 21 he won three Olympic golds in Beijing and broke three world records doing it.",
    "notability": "8× Olympic gold medalist"
  },
  {
    "id": "vlad-tenev",
    "name": "Vlad Tenev",
    "category": "founder",
    "achievement": "Co-founded Robinhood",
    "achievement_year": 2013,
    "age_at_achievement": 26,
    "country_of_origin": "Bulgaria",
    "education_level": "bachelors",
    "education_institution": "Stanford University",
    "prior_failures": [
      "Celeris, his first high-frequency trading firm, failed to find traction",
      "Chronos Research, his second HFT venture, also did not take off"
    ],
    "story": "Bulgarian-born, raised in the US. Dropped out of a UCLA math PhD and watched two of his own trading firms fail. At 26 he started Robinhood, offering commission-free trading when everyone else charged $7 a click.",
    "notability": "$50B peak valuation"
  },
  {
    "id": "walt-disney",
    "name": "Walt Disney",
    "category": "founder",
    "achievement": "Created Mickey Mouse in \"Steamboat Willie\"",
    "achievement_year": 1928,
    "age_at_achievement": 27,
    "country_of_origin": "United States",
    "education_level": "no_college",
    "education_institution": null,
    "prior_failures": [
      "Fired from a Missouri newspaper at 22 for \"lacking imagination\"",
      "His first studio, Laugh-O-Gram, went bankrupt"
    ],
    "story": "Fired by a newspaper editor at 22 for \"lacking imagination.\" Started a studio that went bankrupt. At 27 he created Mickey Mouse with $40 in his pocket.",
    "notability": "Disney Co. now worth $200B+"
  },
  {
    "id": "whitney-wolfe-herd",
    "name": "Whitney Wolfe Herd",
    "category": "founder",
    "achievement": "Founded Bumble",
    "achievement_year": 2014,
    "age_at_achievement": 25,
    "country_of_origin": "United States",
    "education_level": "bachelors",
    "education_institution": "Southern Methodist University",
    "prior_failures": [
      "Pushed out of Tinder at 24 amid a public sexual harassment lawsuit"
    ],
    "story": "Co-founded Tinder, pushed out at 24 in a public, painful lawsuit. Started Bumble at 25, and became the youngest woman to take a US company public.",
    "notability": "$14B peak market cap"
  },
  {
    "id": "zhang-yiming",
    "name": "Zhang Yiming",
    "category": "founder",
    "achievement": "Founded ByteDance (TikTok)",
    "achievement_year": 2012,
    "age_at_achievement": 29,
    "country_of_origin": "China",
    "education_level": "bachelors",
    "education_institution": "Nankai University",
    "prior_failures": [
      "Fanfou, his first startup, was shut down by Chinese censors after just a year",
      "99fang.com, his real-estate startup, did not take off"
    ],
    "story": "Lost his first startup to government censorship. His second flopped. At 29, on his third try, he built ByteDance, the AI-driven content platform that became TikTok.",
    "notability": "$300B+ peak private valuation"
  }
];
